# *******************************GETS******************************

###  USUARIOS
GET http://127.0.0.1:8000/api/p1/users HTTP/1.1
content-type: application/json
Authorization: Bearer 4|lFIy9ntONg3HFvmobK28odlabcIsJhW00eKMYDAD3fca7fca


### MENU
GET http://127.0.0.1:8000/api/p1/menus HTTP/1.1
content-type: application/json
Authorization: Bearer 4|lFIy9ntONg3HFvmobK28odlabcIsJhW00eKMYDAD3fca7fca

### GERENCIAS TODAS
GET http://127.0.0.1:8000/api/p1/gerencias HTTP/1.1
content-type: application/json
Authorization: Bearer 4|lFIy9ntONg3HFvmobK28odlabcIsJhW00eKMYDAD3fca7fca

###  GERENCIA x ID
GET http://127.0.0.1:8000/api/p1/gerencias/1 HTTP/1.1
content-type: application/json
Authorization: Bearer 4|lFIy9ntONg3HFvmobK28odlabcIsJhW00eKMYDAD3fca7fca


###  PEDIDOS
GET http://127.0.0.1:8000/api/p1/pedidos HTTP/1.1
content-type: application/json
Authorization: Bearer 4|lFIy9ntONg3HFvmobK28odlabcIsJhW00eKMYDAD3fca7fca


###  EMPLEADOS
GET http://127.0.0.1:8000/api/p1/empleados HTTP/1.1
content-type: application/json
Authorization: Bearer 4|lFIy9ntONg3HFvmobK28odlabcIsJhW00eKMYDAD3fca7fca

*******************************POSTS******************************

#### LOGIN
POST http://127.0.0.1:8000/api/p1/users/login HTTP/1.1
content-type: application/json


{
    "email": "moicastillo@mercal.gob.ve",
    "password": "12345678"
}


#### USUARIOS
POST http://127.0.0.1:8000/api/p1/users HTTP/1.1
content-type: application/json
Authorization: 

{
    "name": "Moises",
    "email": "moises@example.com",
    "password": "12345678",
    "password_confirmation": "12345678",
    "id_gerencia": 2
}


#### MENUS
POST http://127.0.0.1:8000/api/p1/menus HTTP/1.1
content-type: application/json

{
    "sopa": "Sopa de pescado",
    "contourOne" : "Carne",
    "contourTwo" : "Pollo",
    "saladOne" : "Rayada",
    "saladTwo" : "Rusa",
    "juice" : "Melon",
    "dessert" : "Torta de vainilla"
}

#### PEDIDO
POST http://127.0.0.1:8000/api/p1/pedidos HTTP/1.1
content-type: application/json

{
    "numeroPedido": 1,
    "metodoPagoId" : 1,
    "referencia": 4521,
    "montoTotal": 115,
    "idMenu": 1,
    "idEmpleado": 1
}

#### EMPLEADOS
POST http://127.0.0.1:8000/api/p1/empleados HTTP/1.1
content-type: application/json
Authorization: Bearer 4|lFIy9ntONg3HFvmobK28odlabcIsJhW00eKMYDAD3fca7fca

{
    "nombreCompleto" : "Carlos2 Ramírez",
    "cedula" : "18463444",
    "idGerencia" : 22,
    "estado" : "Miranda",
    "tipoEmpleado" : "fijo",
    "cargo" : "Analista de Proyectos"
}