# *******************************GETS******************************

###  USUARIOS
GET http://comedor.mercal.gob.ve/api/p1/users HTTP/1.1
content-type: application/json
Authorization: Bearer 5|vuxoSKcl1OYHIWySv02ji7jjSUxBtq3uHKqgA4cqeb9ccd56


### MENU
GET http://comedor.mercal.gob.ve/api/p1/menus HTTP/1.1
content-type: application/json
Authorization: Bearer 5|vuxoSKcl1OYHIWySv02ji7jjSUxBtq3uHKqgA4cqeb9ccd56

### EXTRAS
GET http://comedor.mercal.gob.ve/api/p1/extras HTTP/1.1
content-type: application/json
Authorization: Bearer 5|vuxoSKcl1OYHIWySv02ji7jjSUxBtq3uHKqgA4cqeb9ccd56

### GERENCIAS TODAS
GET http://comedor.mercal.gob.ve/api/p1/gerencias HTTP/1.1
content-type: application/json
Authorization: Bearer 5|vuxoSKcl1OYHIWySv02ji7jjSUxBtq3uHKqgA4cqeb9ccd56

###  GERENCIA x ID
GET http://comedor.mercal.gob.ve/api/p1/gerencias/1 HTTP/1.1
content-type: application/json
Authorization: Bearer 5|vuxoSKcl1OYHIWySv02ji7jjSUxBtq3uHKqgA4cqeb9ccd56


###  PEDIDOS
GET http://comedor.mercal.gob.ve/api/p1/pedidos HTTP/1.1
content-type: application/json
Authorization: Bearer 5|vuxoSKcl1OYHIWySv02ji7jjSUxBtq3uHKqgA4cqeb9ccd56

###  PEDIDOS POR ID
GET http://comedor.mercal.gob.ve/api/p1/pedidos/18467449 HTTP/1.1
content-type: application/json
Authorization: Bearer 5|vuxoSKcl1OYHIWySv02ji7jjSUxBtq3uHKqgA4cqeb9ccd56


###  EMPLEADOS
GET http://comedor.mercal.gob.ve/api/p1/empleados HTTP/1.1
content-type: application/json
Authorization: Bearer 5|vuxoSKcl1OYHIWySv02ji7jjSUxBtq3uHKqgA4cqeb9ccd56

*******************************POSTS******************************

#### LOGIN
POST http://comedor.mercal.gob.ve/api/p1/users/login HTTP/1.1
content-type: application/json


{
    "email": "moicastillo@mercal.gob.ve",
    "password": "12345678"
}


#### USUARIOS
POST http://comedor.mercal.gob.ve/api/p1/users HTTP/1.1
content-type: application/json
Authorization: 

{

}


#### MENUS
POST http://comedor.mercal.gob.ve/api/p1/menus/bluk HTTP/1.1
content-type: application/json

[
    {
        "foodCategory": "Sopas",
        "ingredient": "Sopa de Pescado, Sopa de Pollo"
    },
    {
        "foodCategory": "Contornos",
        "ingredient": "Arroz, Pasta"
    },
    {
        "foodCategory": "Proteinas",
        "ingredient": "Carne Molida, Pollo guisado"
    },
    {
        "foodCategory": "Ensaladas",
        "ingredient": "Rayada, Rusa"
    },
    {
        "foodCategory": "Jugos",
        "ingredient": "Melon"
    },
    {
        "foodCategory": "Postres",
        "ingredient": "Torta de Vainilla"
    },
]

#### PEDIDO
POST http://comedor.mercal.gob.ve/api/p1/pedidos HTTP/1.1
content-type: application/json
Authorization: Bearer 5|vuxoSKcl1OYHIWySv02ji7jjSUxBtq3uHKqgA4cqeb9ccd56

{
  "order": {
    "number_order": "1",
    "special_event": "no",
    "authorized" : "no",
    "authorized_person": "no",
    "id_payment_method": "3",
    "reference": "1231231332",
    "total_amount": "100",
    "cedula": "18467449",
    "id_order_status": "1",
    "id_orders_consumption": "1",
    "payment_support": ""
  },
  "extras": [
    "1",
    "2"
  ],
  "employeePayment": {
    "cedula_employee": "18467449",
    "name_employee": "Moises",
    "phone_employee": "0414224547412",
    "management": "22"
  }
}


#### EMPLEADOS
POST "http://comedor.mercal.gob.ve/api/p1/empleados HTTP/1.1
content-type: application/json
Authorization: Bearer 5|vuxoSKcl1OYHIWySv02ji7jjSUxBtq3uHKqgA4cqeb9ccd56

{
    "nombre" : "Carlos",
    "apellido" : "Ramírez",
    "cedula" : "18463448",
    "idGerencia" : 22,
    "estado" : "Miranda",
    "tipoEmpleado" : "fijo",
    "cargo" : "Analista de Proyectos"
}

#### CANTIDAD DE ORDENES POR DIA
GET http://comedor.mercal.gob.ve/api/p1/ordersDay HTTP/1.1
content-type: application/json
Authorization: Bearer 5|vuxoSKcl1OYHIWySv02ji7jjSUxBtq3uHKqgA4cqeb9ccd56

###
POST http://comedor.mercal.gob.ve/api/p1/ordersDay HTTP/1.1
content-type: application/json
Authorization: Bearer 5|vuxoSKcl1OYHIWySv02ji7jjSUxBtq3uHKqgA4cqeb9ccd56

{

    "numberOrdersDay" : 100

}