@baseUrl = "http://10.20.22.88:8000/api/p1"
@authToken = ""


#### 🔐 LOGIN
POST {{baseUrl}}/users/login HTTP/1.1
content-type: application/json

{
    "email": "moicastillo@mercal.gob.ve",
    "password": "12345678"
}

# *******************************GETS******************************

### 👤 USUARIOS
GET {{baseUrl}}/users HTTP/1.1
content-type: application/json
Authorization: Bearer {{authToken}}


### 📋 MENU
GET {{baseUrl}}/menus HTTP/1.1
content-type: application/json
Authorization: Bearer {{authToken}}

### 🏢 GERENCIAS TODAS
GET {{baseUrl}}/gerencias HTTP/1.1
content-type: application/json
Authorization: Bearer {{authToken}}

### 🏢 GERENCIA x ID
GET {{baseUrl}}/gerencias/1 HTTP/1.1
content-type: application/json
Authorization: Bearer {{authToken}}


### 📦 PEDIDOS TODOS
GET {{baseUrl}}/pedidos HTTP/1.1
content-type: application/json
Authorization: Bearer {{authToken}}

### 📦 PEDIDOS por cedula
GET {{baseUrl}}/pedidos/123456 HTTP/1.1
content-type: application/json
Authorization: Bearer {{authToken}}


### 🧑‍💼 EMPLEADOS TODOS
GET {{baseUrl}}/empleados HTTP/1.1
content-type: application/json
Authorization: Bearer {{authToken}}

### 🧑‍💼 EMPLEADOS por Gerencias
GET {{baseUrl}}/empleados?management=22 HTTP/1.1
content-type: application/json
Authorization: Bearer {{authToken}}

### 💵 SCRAPPING BCV
GET {{baseUrl}}/dolar-bcv HTTP/1.1
content-type: application/json
Authorization: Bearer {{authToken}}

### 🏦 BANCOS
GET {{baseUrl}}/bank HTTP/1.1
content-type: application/json
Authorization: Bearer {{authToken}}

### 🔢 ÓRDENES DEL DÍA (GET)
GET {{baseUrl}}/ordersDay HTTP/1.1
content-type: application/json
Authorization: Bearer {{authToken}}

# *******************************POSTS******************************


#### ➕ USUARIOS
POST {{baseUrl}}/users HTTP/1.1
content-type: application/json
# Nota: La autorización no está especificada en tu ejemplo original, se mantiene vacío.
Authorization: 

{
    "name": "Moises",
    "email": "moises@example.com",
    "password": "12345678",
    "password_confirmation": "12345678",
    "id_gerencia": 2
}


#### ➕ MENUS
POST {{baseUrl}}/menus HTTP/1.1
content-type: application/json
# Nota: La autorización no está especificada en tu ejemplo original, se mantiene vacío.

{
    "sopa": "Sopa de pescado",
    "contourOne" : "Carne",
    "contourTwo" : "Pollo",
    "saladOne" : "Rayada",
    "saladTwo" : "Rusa",
    "juice" : "Melon",
    "dessert" : "Torta de vainilla"
}

#### ➕ PEDIDO
POST {{baseUrl}}/pedidos HTTP/1.1
content-type: application/json
# Nota: La autorización no está especificada en tu ejemplo original, se mantiene vacío.

{
    "numeroPedido": 1,
    "metodoPagoId" : 1,
    "referencia": 4521,
    "montoTotal": 115,
    "idMenu": 1,
    "idEmpleado": 1
}

#### ➕ EMPLEADOS
POST {{baseUrl}}/empleados HTTP/1.1
content-type: application/json
Authorization: Bearer {{authToken}}

{
    "nombreCompleto" : "Carlos2 Ramírez",
    "cedula" : "18463444",
    "idGerencia" : 22,
    "estado" : "Miranda",
    "tipoEmpleado" : "fijo",
    "cargo" : "Analista de Proyectos"
}

#### ➕ ÓRDENES DEL DÍA (POST)
POST {{baseUrl}}/ordersDay HTTP/1.1
content-type: application/json
Authorization: Bearer {{authToken}}

{
    "numberOrdersDay" : 20
}