@baseUrl = https://comedor.mercal.gob.ve/api/p1
@authToken = 2|McEylzLhPRZK06IGfkmMHmwQHLR2w32xmAA4u3I86b795a04

# *******************************GETS******************************

###  USUARIOS
GET {{baseUrl}}/users HTTP/1.1
content-type: application/json
Authorization: Bearer {{authToken}}


### MENU
GET {{baseUrl}}/menus HTTP/1.1
content-type: application/json
Authorization: Bearer {{authToken}}

### EXTRAS
GET {{baseUrl}}/extras HTTP/1.1
content-type: application/json
Authorization: Bearer {{authToken}}

### GERENCIAS TODAS
GET {{baseUrl}}/gerencias HTTP/1.1
content-type: application/json
Authorization: Bearer {{authToken}}

###  GERENCIA x ID
GET {{baseUrl}}/gerencias/1 HTTP/1.1
content-type: application/json
Authorization: Bearer {{authToken}}


###  PEDIDOS
GET {{baseUrl}}/pedidos HTTP/1.1
content-type: application/json
Authorization: Bearer {{authToken}}

###  PEDIDOS POR ID
GET {{baseUrl}}/pedidos/18467449 HTTP/1.1
content-type: application/json
Authorization: Bearer {{authToken}}


###  PEDIDOS POR ORDEN
GET {{baseUrl}}/pedidos/takeOrder/8 HTTP/1.1
content-type: application/json
Authorization: Bearer {{authToken}}


###  METODOS DE PAGO
GET {{baseUrl}}/metodosPagos HTTP/1.1
content-type: application/json
Authorization: Bearer {{authToken}}


###  EMPLEADOS
GET {{baseUrl}}/empleados HTTP/1.1
content-type: application/json
Authorization: Bearer {{authToken}}

*******************************POSTS******************************

#### LOGIN
POST {{baseUrl}}/users/login HTTP/1.1
content-type: application/json

{
    "email": "moicastillo@mercal.gob.ve",
    "password": "12345678"
}


#### PEDIDO
POST {{baseUrl}}/pedidos HTTP/1.1
content-type: application/json
Authorization: Bearer {{authToken}}

{
  "order": {
    "authorized" : "no",
    "authorized_person": "no",
    "id_payment_method": "2",
    "reference": "1231231332",
    "total_amount": "100",
    "cedula": "18467449",
    "id_order_status": "1",
    "id_orders_consumption": "1",
    "payment_support": "foto.png"
  },
  "extras": [
    "1",
    "2"
  ],
  "employeePayment": {
    "cedula_employee": "18467449",
    "name_employee": "Moises",
    "phone_employee": "0414224547412",
    "management": "22"
  }
}


#### CANTIDAD DE ORDENES POR DIA
GET {{baseUrl}}/ordersDay HTTP/1.1
content-type: application/json
Authorization: Bearer {{authToken}}

###
POST {{baseUrl}}/ordersDay HTTP/1.1
content-type: application/json
Authorization: Bearer {{authToken}}

{"numberOrdersDay" : 100}


#### BANCOS
GET https://comedor.mercal.gob.ve/api/p1/bank HTTP/1.1
content-type: application/json
Authorization: Bearer {{authToken}}